package FixMyStreet::Geocode::Address;

use strict;
use warnings;

use overload '""' => \&as_string, fallback => 1;

sub new {
    my ($class, $data) = @_;
    my $self = { %$data };
    bless $self, $class;
}


sub brand { "Bing Maps" }

sub name_key { "name" }


sub as_string {
    my $self = shift;

    my $data = sprintf(_("Nearest road to the pin placed on the map (automatically generated by %s): %s"),
        $self->brand, $self->{$self->name_key}) . "\n\n";

    if ($self->{postcode}) {
        $data .= sprintf(_("Nearest postcode to the pin placed on the map (automatically generated): %s (%sm away)"),
            $self->{postcode}{postcode}, $self->{postcode}{distance}) . "\n\n";
    }

    return $data;
}

1;
