package BarnetTypes::BAPI_TTET_ADDRESS_COM;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'urn:sap-com:document:sap:rfc:functions' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %COUNTRY2_of :ATTR(:get<COUNTRY2>);
my %REGION_of :ATTR(:get<REGION>);
my %COUNTY_of :ATTR(:get<COUNTY>);
my %CITY_of :ATTR(:get<CITY>);
my %POSTALCODE_of :ATTR(:get<POSTALCODE>);
my %STREET_of :ATTR(:get<STREET>);
my %STREETNUMBER_of :ATTR(:get<STREETNUMBER>);
my %GEOCODE_of :ATTR(:get<GEOCODE>);

__PACKAGE__->_factory(
    [ qw(        COUNTRY2
        REGION
        COUNTY
        CITY
        POSTALCODE
        STREET
        STREETNUMBER
        GEOCODE

    ) ],
    {
        'COUNTRY2' => \%COUNTRY2_of,
        'REGION' => \%REGION_of,
        'COUNTY' => \%COUNTY_of,
        'CITY' => \%CITY_of,
        'POSTALCODE' => \%POSTALCODE_of,
        'STREET' => \%STREET_of,
        'STREETNUMBER' => \%STREETNUMBER_of,
        'GEOCODE' => \%GEOCODE_of,
    },
    {
        'COUNTRY2' => 'BarnetTypes::char2',
        'REGION' => 'BarnetTypes::char3',
        'COUNTY' => 'BarnetTypes::char30',
        'CITY' => 'BarnetTypes::char30',
        'POSTALCODE' => 'BarnetTypes::char10',
        'STREET' => 'BarnetTypes::char30',
        'STREETNUMBER' => 'BarnetTypes::char5',
        'GEOCODE' => 'BarnetTypes::char32',
    },
    {

        'COUNTRY2' => 'COUNTRY2',
        'REGION' => 'REGION',
        'COUNTY' => 'COUNTY',
        'CITY' => 'CITY',
        'POSTALCODE' => 'POSTALCODE',
        'STREET' => 'STREET',
        'STREETNUMBER' => 'STREETNUMBER',
        'GEOCODE' => 'GEOCODE',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

BarnetTypes::BAPI_TTET_ADDRESS_COM

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
BAPI_TTET_ADDRESS_COM from the namespace urn:sap-com:document:sap:rfc:functions.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * COUNTRY2


=item * REGION


=item * COUNTY


=item * CITY


=item * POSTALCODE


=item * STREET


=item * STREETNUMBER


=item * GEOCODE




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # BarnetTypes::BAPI_TTET_ADDRESS_COM
   COUNTRY2 => $some_value, # char2
   REGION => $some_value, # char3
   COUNTY => $some_value, # char30
   CITY => $some_value, # char30
   POSTALCODE => $some_value, # char10
   STREET => $some_value, # char30
   STREETNUMBER => $some_value, # char5
   GEOCODE => $some_value, # char32
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

