package BarnetTypes::TABLE_OF_CRMT_SERVICE_REQUEST_TEXT;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'urn:sap-com:document:sap:rfc:functions' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %item_of :ATTR(:get<item>);

__PACKAGE__->_factory(
    [ qw(        item

    ) ],
    {
        'item' => \%item_of,
    },
    {
        'item' => 'BarnetTypes::CRMT_SERVICE_REQUEST_TEXT',
    },
    {

        'item' => 'item',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

BarnetTypes::TABLE_OF_CRMT_SERVICE_REQUEST_TEXT

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
TABLE_OF_CRMT_SERVICE_REQUEST_TEXT from the namespace urn:sap-com:document:sap:rfc:functions.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * item




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # BarnetTypes::TABLE_OF_CRMT_SERVICE_REQUEST_TEXT
   item =>  { # BarnetTypes::CRMT_SERVICE_REQUEST_TEXT
     TEXT_LINE => $some_value, # char132
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

