package BarnetTypes::RfcException::Message;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'urn:sap-com:document:sap:rfc:functions' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ID_of :ATTR(:get<ID>);
my %Number_of :ATTR(:get<Number>);

__PACKAGE__->_factory(
    [ qw(        ID
        Number

    ) ],
    {
        'ID' => \%ID_of,
        'Number' => \%Number_of,
    },
    {
        'ID' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Number' => 'BarnetTypes::RfcException::Message::Number',
    },
    {

        'ID' => 'ID',
        'Number' => 'Number',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

BarnetTypes::RfcException::Message

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
RfcException.Message from the namespace urn:sap-com:document:sap:rfc:functions.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ID


=item * Number




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # BarnetTypes::RfcException::Message
   ID =>  $some_value, # string
   Number => $some_value, # RfcException.Message.Number
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

