#!/bin/bash

set -e

cd "$(dirname "$0")/.."

normalize_bind_mounted_scripts() {
    find docker script bin commonlib/bin commonlib/shlib -type f 2>/dev/null | while read -r file; do
        first_line=$(sed -n '1p' "$file")
        case "$first_line" in
            '#!'*)
                perl -0pi -e 's/\r\n/\n/g' "$file"
                ;;
        esac
    done
}

normalize_bind_mounted_scripts

seed_fixture_photos() {
    mkdir -p ../upload
    find t/images -type f | while read -r file; do
        sum=$(sha1sum "$file" | cut -d' ' -f1)
        ext=${file##*.}
        case "$ext" in
            jpg|jpeg)
                ext=jpeg
                ;;
            tif)
                ext=tiff
                ;;
        esac
        cp "$file" "../upload/$sum.$ext"
    done
}

if [ ! -f conf/general.yml ]; then
    sed -r \
        -e "s,^( *FMS_DB_HOST:).*,\\1 'postgres.svc'," \
        -e "s,^( *FMS_DB_NAME:).*,\\1 'fixmystreet'," \
        -e "s,^( *FMS_DB_USER:).*,\\1 'postgres'," \
        -e "s,^( *FMS_DB_PASS:).*,\\1 'password'," \
        -e "s,^( *BASE_URL:).*,\\1 'http://127.0.0.1.nip.io:3000'," \
        -e "s,^( *MAPIT_URL:).*,\\1 'http://localhost:3000/fakemapit/'," \
        -e "s,^( *MEMCACHED_HOST:).*,\\1 'memcached.svc'," \
        -e "s,^( *SMTP_SMARTHOST:).*,\\1 'email.svc'," \
        -e "s,^( *SMTP_PORT:).*,\\1 '1025'," \
        conf/general.yml-example > conf/general.yml
fi

script/update --development
seed_fixture_photos
perl bin/fixmystreet.com/tyseley-fixture --commit
bin/update-all-reports
