package BarnetTypes::Z_CRM_SERVICE_ORDER_CREATE::RfcException;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'urn:sap-com:document:sap:rfc:functions' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Name_of :ATTR(:get<Name>);
my %Text_of :ATTR(:get<Text>);
my %Message_of :ATTR(:get<Message>);

__PACKAGE__->_factory(
    [ qw(        Name
        Text
        Message

    ) ],
    {
        'Name' => \%Name_of,
        'Text' => \%Text_of,
        'Message' => \%Message_of,
    },
    {
        'Name' => 'BarnetTypes::Z_CRM_SERVICE_ORDER_CREATE::RfcExceptions',
        'Text' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Message' => 'BarnetTypes::RfcException::Message',
    },
    {

        'Name' => 'Name',
        'Text' => 'Text',
        'Message' => 'Message',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

BarnetTypes::Z_CRM_SERVICE_ORDER_CREATE::RfcException

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Z_CRM_SERVICE_ORDER_CREATE.RfcException from the namespace urn:sap-com:document:sap:rfc:functions.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Name


=item * Text


=item * Message




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # BarnetTypes::Z_CRM_SERVICE_ORDER_CREATE::RfcException
   Name => $some_value, # Z_CRM_SERVICE_ORDER_CREATE.RfcExceptions
   Text =>  $some_value, # string
   Message =>  { # BarnetTypes::RfcException::Message
     ID =>  $some_value, # string
     Number => $some_value, # RfcException.Message.Number
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

