#!/usr/bin/env python

import os
import sys
import tarfile
import urllib
from utils import get_bundle_filename

wanted_filename = get_bundle_filename()

url = 'https://fixmystreet-bundle-cache.s3.amazonaws.com/%s' % wanted_filename
try:
    urllib.urlretrieve(url, wanted_filename)
    if tarfile.is_tarfile(wanted_filename):
        tfile = tarfile.open(wanted_filename)
        tfile.extractall()
        print "Cached copy found and extracted"
        sys.exit(0)
    else:
        os.remove(wanted_filename)
except IOError:
    os.remove(wanted_filename)

print "No cached copy found, running carton install..."
ret = os.system('vendor/bin/carton install --deployment')
if ret:
    os.system('cat ~/.cpanm/build.log')

sys.exit(ret)
