ALTER TABLE token RENAME COLUMN data TO data_json;
ALTER TABLE token ADD COLUMN data bytea;
ALTER TABLE report_extra_fields RENAME COLUMN extra TO extra_json;
ALTER TABLE report_extra_fields ADD COLUMN extra text;
ALTER TABLE defect_types RENAME COLUMN extra TO extra_json;
ALTER TABLE defect_types ADD COLUMN extra text;
ALTER TABLE moderation_original_data RENAME COLUMN extra TO extra_json;
ALTER TABLE moderation_original_data ADD COLUMN extra text;
ALTER TABLE comment RENAME COLUMN extra TO extra_json;
ALTER TABLE comment ADD COLUMN extra text;
ALTER TABLE problem RENAME COLUMN geocode TO geocode_json;
ALTER TABLE problem ADD COLUMN geocode bytea;
ALTER TABLE problem RENAME COLUMN extra TO extra_json;
ALTER TABLE problem ADD COLUMN extra text;
ALTER TABLE contacts RENAME COLUMN extra TO extra_json;
ALTER TABLE contacts ADD COLUMN extra text;
ALTER TABLE body RENAME COLUMN extra TO extra_json;
ALTER TABLE body ADD COLUMN extra text;
ALTER TABLE users RENAME COLUMN extra TO extra_json;
ALTER TABLE users ADD COLUMN extra text;
