ALTER TABLE users DROP COLUMN extra;
ALTER TABLE users RENAME COLUMN extra_json TO extra;
ALTER TABLE body DROP COLUMN extra;
ALTER TABLE body RENAME COLUMN extra_json TO extra;
ALTER TABLE contacts DROP COLUMN extra;
ALTER TABLE contacts RENAME COLUMN extra_json TO extra;
ALTER TABLE problem DROP COLUMN extra;
ALTER TABLE problem RENAME COLUMN extra_json TO extra;
ALTER TABLE problem DROP COLUMN geocode;
ALTER TABLE problem RENAME COLUMN geocode_json TO geocode;
ALTER TABLE comment DROP COLUMN extra;
ALTER TABLE comment RENAME COLUMN extra_json TO extra;
ALTER TABLE moderation_original_data DROP COLUMN extra;
ALTER TABLE moderation_original_data RENAME COLUMN extra_json TO extra;
ALTER TABLE defect_types DROP COLUMN extra;
ALTER TABLE defect_types RENAME COLUMN extra_json TO extra;
ALTER TABLE report_extra_fields DROP COLUMN extra;
ALTER TABLE report_extra_fields RENAME COLUMN extra_json TO extra;
ALTER TABLE token DROP COLUMN data;
ALTER TABLE token RENAME COLUMN data_json TO data;
