#!/bin/sh

set -e
cd "$(dirname "$0")/.."

git submodule --quiet update --init --recursive --rebase

# Let's see if we can't work out where we might be running.
if cut -d/ -f2 /proc/self/cgroup | sort -u | grep -q docker ; then
    if [ -z ${SKIP_PACKAGES_INSTALL:+x} ] ; then
        echo "==> Installing Docker packages..."
        sudo bin/install_packages docker
    fi
else
    # Fallback
    echo "==> Installing generic packages..."
    sudo bin/install_packages generic
fi

bin/install_perl_modules
