#!/bin/bash
#
# By default, if no arguments given, runs a server on port 3000 with
# auto-reloading, and debug switched on. Run with FIXMYSTREET_APP_DEBUG=0 to
# override debug, or provide arguments to override everything.

set -e
cd "$(dirname "$0")/.."

if [ -z "$1" ]; then
    export FIXMYSTREET_APP_DEBUG=${FIXMYSTREET_APP_DEBUG=1}
    set -- --listen :3000 --Reload perllib,conf
fi

DWARN=""
if [ -n "$FIXMYSTREET_APP_DEBUG" -a "$FIXMYSTREET_APP_DEBUG" != "0" ]; then
    DWARN="-MDevel::Dwarn"
fi

bin/cron-wrapper perl $DWARN local/bin/plackup -s Starman $@
