package BarnetInterfaces::service::ZLBB_SERVICE_ORDER;
use strict;
use warnings;
use Class::Std::Fast::Storable;
use Scalar::Util qw(blessed);
use base qw(SOAP::WSDL::Client::Base);

# only load if it hasn't been loaded before
require BarnetTypemaps::service
    if not BarnetTypemaps::service->can('get_class');

sub START {
    $_[0]->set_proxy('http://lbbcrmdev.barnet.gov.uk:8000/sap/bc/srt/rfc/sap/zlbb_service_order/200/zlbb_service_order/zlbb_service_order') if not $_[2]->{proxy};
    $_[0]->set_class_resolver('BarnetTypemaps::service')
        if not $_[2]->{class_resolver};

    $_[0]->set_prefix($_[2]->{use_prefix}) if exists $_[2]->{use_prefix};
}

sub Z_CRM_SERVICE_ORDER_CREATE {
    my ($self, $body, $header) = @_;
    die "Z_CRM_SERVICE_ORDER_CREATE must be called as object method (\$self is <$self>)" if not blessed($self);
    return $self->SUPER::call({
        operation => 'Z_CRM_SERVICE_ORDER_CREATE',
        soap_action => '',
        style => 'document',
        body => {
            

           'use'            => 'literal',
            namespace       => 'http://schemas.xmlsoap.org/wsdl/soap/',
            encodingStyle   => '',
            parts           =>  [qw( BarnetElements::Z_CRM_SERVICE_ORDER_CREATE )],
        },
        header => {
            
        },
        headerfault => {
            
        }
    }, $body, $header);
}




1;



__END__

=pod

=head1 NAME

BarnetInterfaces::service::ZLBB_SERVICE_ORDER - SOAP Interface for the service Web Service

=head1 SYNOPSIS

 use BarnetInterfaces::service::ZLBB_SERVICE_ORDER;
 my $interface = BarnetInterfaces::service::ZLBB_SERVICE_ORDER->new();

 my $response;
 $response = $interface->Z_CRM_SERVICE_ORDER_CREATE();



=head1 DESCRIPTION

SOAP Interface for the service web service
located at http://lbbcrmdev.barnet.gov.uk:8000/sap/bc/srt/rfc/sap/zlbb_service_order/200/zlbb_service_order/zlbb_service_order.

=head1 SERVICE service



=head2 Port ZLBB_SERVICE_ORDER



=head1 METHODS

=head2 General methods

=head3 new

Constructor.

All arguments are forwarded to L<SOAP::WSDL::Client|SOAP::WSDL::Client>.

=head2 SOAP Service methods

Method synopsis is displayed with hash refs as parameters.

The commented class names in the method's parameters denote that objects
of the corresponding class can be passed instead of the marked hash ref.

You may pass any combination of objects, hash and list refs to these
methods, as long as you meet the structure.

List items (i.e. multiple occurences) are not displayed in the synopsis.
You may generally pass a list ref of hash refs (or objects) instead of a hash
ref - this may result in invalid XML if used improperly, though. Note that
SOAP::WSDL always expects list references at maximum depth position.

XML attributes are not displayed in this synopsis and cannot be set using
hash refs. See the respective class' documentation for additional information.



=head3 Z_CRM_SERVICE_ORDER_CREATE



Returns a L<BarnetElements::Z_CRM_SERVICE_ORDER_CREATEResponse|BarnetElements::Z_CRM_SERVICE_ORDER_CREATEResponse> object.

 $response = $interface->Z_CRM_SERVICE_ORDER_CREATE( {
    ET_RETURN =>  { # BarnetTypes::TABLE_OF_BAPIRET2
      item =>  { # BarnetTypes::BAPIRET2
        TYPE => $some_value, # char1
        ID => $some_value, # char20
        NUMBER => $some_value, # numeric3
        MESSAGE => $some_value, # char220
        LOG_NO => $some_value, # char20
        LOG_MSG_NO => $some_value, # numeric6
        MESSAGE_V1 => $some_value, # char50
        MESSAGE_V2 => $some_value, # char50
        MESSAGE_V3 => $some_value, # char50
        MESSAGE_V4 => $some_value, # char50
        PARAMETER => $some_value, # char32
        ROW =>  $some_value, # int
        FIELD => $some_value, # char30
        SYSTEM => $some_value, # char10
      },
    },
    IT_PROBLEM_DESC =>  { # BarnetTypes::TABLE_OF_CRMT_SERVICE_REQUEST_TEXT
      item =>  { # BarnetTypes::CRMT_SERVICE_REQUEST_TEXT
        TEXT_LINE => $some_value, # char132
      },
    },
    IV_CUST_EMAIL => $some_value, # char241
    IV_CUST_NAME => $some_value, # char50
    IV_KBID => $some_value, # char50
    IV_PROBLEM_ID => $some_value, # char35
    IV_PROBLEM_LOC =>  { # BarnetTypes::BAPI_TTET_ADDRESS_COM
      COUNTRY2 => $some_value, # char2
      REGION => $some_value, # char3
      COUNTY => $some_value, # char30
      CITY => $some_value, # char30
      POSTALCODE => $some_value, # char10
      STREET => $some_value, # char30
      STREETNUMBER => $some_value, # char5
      GEOCODE => $some_value, # char32
    },
    IV_PROBLEM_SUB => $some_value, # char40
  },,
 );



=head1 AUTHOR

Generated by SOAP::WSDL on Fri Apr  8 10:23:03 2011

=cut
