FROM jgoerzen/debian-base-standard:stretch AS perl-modules
MAINTAINER bettercities@mysociety.org
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update \
	&& apt-get -qq -y install --no-install-recommends apt-utils \
	&& apt-get -qq -y install git
RUN mkdir -p /var/www/fixmystreet
RUN git clone --recursive --branch docker git://github.com/mysociety/fixmystreet.git /var/www/fixmystreet/fixmystreet
RUN xargs -a "/var/www/fixmystreet/fixmystreet/conf/packages.docker" apt-get -qq -y install
RUN cd /var/www/fixmystreet/fixmystreet && bin/install_perl_modules


FROM jgoerzen/debian-base-standard:stretch
MAINTAINER bettercities@mysociety.org

ARG DEBIAN_FRONTEND=noninteractive
ARG REPOSITORY_URL_OVERRIDE=git://github.com/mysociety/fixmystreet.git
ARG BRANCH_OVERRIDE=docker-no-install-perl

RUN apt-get -qq update \
	&& apt-get -qq -y install --no-install-recommends apt-utils \
	&& apt-get -qq -y install git
RUN mkdir -p /var/www/fixmystreet
RUN git clone --recursive --branch docker git://github.com/mysociety/fixmystreet.git /var/www/fixmystreet/fixmystreet
COPY --from=perl-modules /var/www/fixmystreet/fixmystreet/local /var/www/fixmystreet/fixmystreet/local

RUN apt-get -qq update && apt-get -qq -y install --no-install-recommends apt-utils && apt-get -qq -y install git locales

RUN wget -O install-site.sh --no-verbose https://raw.githubusercontent.com/mysociety/commonlib/docker/bin/install-site.sh && chmod +x /install-site.sh

RUN /install-site.sh --docker fixmystreet fms 127.0.0.1.xip.io

RUN cp /var/www/fixmystreet/fixmystreet/bin/docker.preinit /usr/local/preinit/99-fixmystreet && chmod +x /usr/local/preinit/99-fixmystreet

EXPOSE 9000
CMD ["/usr/local/bin/boot-debian-base"]
